### PR TITLE
Import patches from FreeBSD port

### PR DESCRIPTION
**Pull request by outpaddling**
This fork contains all the patches necessary for the FreeBSD port, and lays the foundation for porting to other BSDs.
Since most of the OS checks were alphabetized, I also took the liberty of reorganizing those that we not.

### CODE REVIEW

**Comment by klymenko** [comment]
@outpaddling, how did you build it?

**Comment by outpaddling** [comment]
Using the FreeBSD ports system.  This is how virtually all software is installed on FreeBSD.

My work-in-progress ports collection contains the latest:

[https://github.com/outpaddling/freebsd-ports-wip](https://github.com/outpaddling/freebsd-ports-wip)

The "sra-tools-fork" port uses this fork, so the port framework has to do minimal patching (see the REINPLACE_CMDs in the port Makefile).  The regular "sra-tools" port contains all of the patches in this fork in the files directory, and applies them automatically after the dist is extracted.

**Comment by klymenko** [comment]
@outpaddling, this PR was merged into engineering branch, as well.

**Comment by outpaddling** [comment]
Yeah, I saw that.  FYI, I'm updating the pkgsrc package now and the NetBSD build caught one more missing header in the latest engineering commit.

```
--- ncbi-vdb/libs/kdbtext/path.hpp.orig 2024-03-21 22:06:49.815904250 +0000
+++ ncbi-vdb/libs/kdbtext/path.hpp
@@ -28,6 +28,7 @@
 
 #include <string>
 #include <queue>
+#include <cstdarg>
 
 #include <klib/rc.h>
```

**Comment by klymenko** [comment]
This pull request was merged.

**Pull request closed without merging**
