### PR TITLE
FreeBSD compatibility patches

### PR DESCRIPTION
**Pull request by yurivict**
Upstreaming patches from the FreeBSD port.

### CODE REVIEW

**Comment by klymenko** [comment]
What are your `configure` and `make` commands to build it?

**Comment by yurivict** [comment]
configure:
```
MAKE=gmake ac_cv_path_PERL=/usr/local/bin/perl ac_cv_path_PERL_PATH=/usr/local/bin/perl  PERL_USE_UNSAFE_INC=1 XDG_DATA_HOME=/disk-samsung/freebsd-ports/biology/ncbi-vdb/work  XDG_CONFIG_HOME=/disk-samsung/freebsd-ports/biology/ncbi-vdb/work  HOME=/disk-samsung/freebsd-ports/biology/ncbi-vdb/work PATH=/disk-samsung/freebsd-ports/biology/ncbi-vdb/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin SHELL=/bin/sh CONFIG_SHELL=/bin/sh CMAKE_PREFIX_PATH="/usr/local" CONFIG_SITE=/disk-samsung/freebsd-ports/Templates/config.site lt_cv_sys_max_cmd_len=524288 \
./configure \
--with-xml2-prefix=/usr/local  --with-hdf5-prefix=/usr/local  --with-mbedtls-prefix=/usr/local  CC="cc" CXX="c++" TOOLS="clang" --prefix=/usr/local
```

make:
```
PERL_USE_UNSAFE_INC=1 XDG_DATA_HOME=/disk-samsung/freebsd-ports/biology/ncbi-vdb/work  XDG_CONFIG_HOME=/disk-samsung/freebsd-ports/biology/ncbi-vdb/work  HOME=/disk-samsung/freebsd-ports/biology/ncbi-vdb/work PATH=/disk-samsung/freebsd-ports/biology/ncbi-vdb/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe -fno-omit-frame-pointer  -I/disk-samsung/freebsd-ports/biology/ncbi-vdb/work/ncbi-vdb-2.11.0/lib -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing "  CPP="cpp" CPPFLAGS="-fno-omit-frame-pointer -isystem /usr/local/include"  LDFLAGS=" -fstack-protector-strong -L/usr/local/lib " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fno-omit-frame-pointer -I/disk-samsung/freebsd-ports/biology/ncbi-vdb/work/ncbi-vdb-2.11.0/lib -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include "  MANPREFIX="/usr/local" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" \
gmake \
CCNAME=cc CXXNAME=c++ PKGCFLAGS="-O2 -pipe -fno-omit-frame-pointer  -I/disk-samsung/freebsd-ports/biology/ncbi-vdb/work/ncbi-vdb-2.11.0/lib -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing " DESTDIR=/disk-samsung/freebsd-ports/biology/ncbi-vdb/work/stage
```

**Comment by klymenko** [comment]
It fails to build: `ncbi-vdb/build/Makefile.bsd` does not exist.
Here is the start of output of `gmake -d` in `ncbi-vdb/libs/kfc`:
```
GNU Make 4.3
Built for amd64-portbld-freebsd12.1
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Reading makefile 'Makefile'...
Reading makefile '/usr/home/klymenko/src/ncbi-vdb/build/Makefile.env' (search path) (no ~ expansion)...
Reading makefile '/usr/home/klymenko/src/ncbi-vdb/build/Makefile.shell' (search path) (no ~ expansion)...
Reading makefile '/usr/home/klymenko/src/ncbi-vdb/build/Makefile.config' (search path) (no ~ expansion)...
Reading makefile '/usr/home/klymenko/src/ncbi-vdb/build/Makefile.config.bsd.x86_64' (search path) (no ~ expansion)...
Reading makefile '/usr/home/klymenko/src/ncbi-vdb/build/Makefile.vers' (search path) (no ~ expansion)...
Reading makefile '/usr/home/klymenko/src/ncbi-vdb/build/Makefile.bsd' (search path) (no ~ expansion)...
...
```
The last one cannot be found.
Error message is:
```
/usr/home/klymenko/src/ncbi-vdb/build/Makefile.env:83: /usr/home/klymenko/src/ncbi-vdb/build/Makefile.bsd: No such file or directory
gmake: *** No rule to make target '/usr/home/klymenko/src/ncbi-vdb/build/Makefile.bsd'.  Stop.
```
Line `83` of `Makefile.env` is `include $(TOP)/build/Makefile.$(OS)`.

**Comment by outpaddling** [comment]
I'm attaching a new set of patches required for a successful build of 3.0.2 and headers for populating interfaces/os/freebsd.  The patches are simple, but if you prefer a pull request I can do that.

[ncbi-vdb-patches.tar.gz](https://github.com/ncbi/ncbi-vdb/files/10562737/ncbi-vdb-patches.tar.gz)

**Comment by klymenko** [comment]
Newer pull request https://github.com/ncbi/ncbi-vdb/pull/112 was merged.

**Pull request closed without merging**
